{{- if .Values.FinanceWiseServices.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.FinanceWiseServices.name }}
  namespace: {{ .Values.global.namespace }}
data:
  plugin-profiles.json: |
    {
        "fwise-oidc":{
    
            "oauth2":{
                "version": 1,
                "discovery_url": "{{ .Values.FinanceWiseServices.keycloak.well_known_url }}",
                "client_id": "{{ .Values.FinanceWiseServices.keycloak.client_id }}",
                "client_secret": "{{ .Values.FinanceWiseServices.keycloak.client_secret }}"
            },
    
            "copyTokenClaims":{
                "version": 1,
                "fields":[
                    {"from":"clientId", "to":"tenantId"},
                    {"from":"cpf", "to":"cpf"}
                ]
            }
    
        }
    }

{{- end}}