{{- if .Values.AdminPortal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.AdminPortal.name }}
  namespace: {{ .Values.global.namespace }}
  {{- if .Values.global.monitoring.datadog.enabled }}
  labels:
    tags.datadoghq.com/env: "{{ .Values.global.monitoring.datadog.env }}"
    tags.datadoghq.com/service: "{{ .Values.AdminPortal.name }}"
    tags.datadoghq.com/version: "{{ .Values.AdminPortal.image.tag }}"
  {{- end}}
spec:
  replicas: {{ .Values.AdminPortal.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.AdminPortal.name | quote }}
  strategy:
    type: {{ .Values.AdminPortal.updateStrategy }}
  template:
    metadata:
      annotations:
    metadata:
      labels:
        app: {{ .Values.AdminPortal.name | quote }}
      {{- if .Values.global.monitoring.datadog.enabled }}
        tags.datadoghq.com/env: "{{ .Values.global.monitoring.datadog.env }}"
        tags.datadoghq.com/service: "{{ .Values.AdminPortal.name }}"
        tags.datadoghq.com/version: "{{ .Values.AdminPortal.image.tag }}"
      {{- end}}
    spec:
      containers:
      - name: {{ .Values.AdminPortal.name | quote }}
        image: {{ .Values.AdminPortal.image.repository }}/{{ .Values.AdminPortal.image.name }}:{{ .Values.AdminPortal.image.tag }}
        imagePullPolicy: {{ .Values.AdminPortal.image.pullPolicy }}

        env:
        {{- with .Values.AdminPortal.env }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

        # DATADOG ENV'S
        {{- if .Values.global.monitoring.datadog.enabled }}
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_SAMPLE_RATE
          value: "1"
        - name: DD_PROFILING_ENABLED
          value: "false"
        - name: DD_TAGS
          value: "tennant:{{ .Values.global.monitoring.datadog.tennant}}"
        - name: DD_TRACE_DEBUG
          value: "{{ .Values.global.monitoring.datadog.debug }}"
        {{- end}}

        command:
          - /bin/sh
        args:
          - '-c'
          - node index.js

        ports:
        - containerPort: {{ .Values.AdminPortal.apiPort }}
          protocol: TCP

        {{- with .Values.AdminPortal.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}

        {{- with .Values.AdminPortal.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}

        {{- with .Values.AdminPortal.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}

        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

      {{- with .Values.AdminPortal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.AdminPortal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.AdminPortal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
        {{- end }}

      dnsConfig:
        options:
          - name: ndots
            value: '1'
      dnsPolicy: ClusterFirst

      restartPolicy: Always

      schedulerName: default-scheduler


      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}

status: {}
{{- end}}