#
autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  ## targetCPUUtilizationPercentage only used if the cluster doesn't support autoscaling/v2beta
  targetCPUUtilizationPercentage:
  ## Otherwise for clusters that do support autoscaling/v2beta, use metrics
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

global:
  clusterDomain: cluster.local
  updateStrategy: "RollingUpdate"
  editor: "FinanceWise"
  namespace: "financewise"
  domainName: "dev.example.com"
  pullPolicy: Always
  imagePullSecrets:
  - name: regsecret

  monitoring:
    datadog:
      enabled: false
      env: env_name
      tennant: client_name
      debug: false

###################
FinanceWhatsappApi:
  enabled: true
  name: fw-whatsapp-api
  updateStrategy: "RollingUpdate"
  image:
    repository: fwinternal.azurecr.io
    name: fw-whatsapp-api
    tag: 2d5a1f15d4140a5e67287894722ac4baef2a3c49
    pullPolicy: Always

  replicaCount: 1

  apiPort: 3000

  env:
    - name: PORT
      value: 3000
    - name: API_KEY
      value: your_global_api_key_here
    - name: BASE_WEBHOOK_URL
      value: http://localhost:3000/localCallbackExample
    - name: ENABLE_LOCAL_CALLBACK_EXAMPLE
      value: FALSE
    - name: RATE_LIMIT_MAX
      value: 1000
    - name: RATE_LIMIT_WINDOW_MS
      value: 1000
    - name: MAX_ATTACHMENT_SIZE
      value: 10000000
    - name: SET_MESSAGES_AS_SEEN
      value: TRUE
    - name: DISABLED_CALLBACKS
      value: auth_failure|authenticated|call|change_state|disconnected|group_join|group_leave|group_update|loading_screen|media_uploaded|message|message_ack|message_create|message_reaction|message_revoke_everyone|qr|ready|contact_changed|unread_count|message_edit|message_ciphertext
    - name: WEB_VERSION
      value: 2.2328.5
    - name: WEB_VERSION_CACHE_TYPE
      value: none
    - name: RECOVER_SESSIONS
      value: FALSE
    - name: ENABLE_SWAGGER_ENDPOINT
      value: FALSE


  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
    hosts:
      - host: whatsapp-api.dev.example.com
        paths:
          - /
    tls:
     - secretName: whatsapp-api.dev.example.com
       hosts:
         - whatsapp-api.dev.example.com


  resources:
    requests:
      cpu: 200m
      memory: 1000Mi
    limits:
      cpu: 3000m
      memory: 1000Mi

  readinessProbe:
    tcpSocket:
      port: 3000
    initialDelaySeconds: 60
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 5

  livenessProbe:
    tcpSocket:
      port: 3000
    initialDelaySeconds: 60
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

  nodeSelector: {}

  tolerations: []

  affinity: {}