apiVersion: v1
appVersion: 0.1.2
description: financewise-data-aggregator-services
keywords:
- financewise
maintainers:
- email: infra@financewise.app.br
  name: financewise-data-aggregator-services
name: financewise-data-aggregator-services
version: 0.1.2