FinanceWiseServices:
  affinity: {}
  apiPort: 3000
  enabled: true
  env:
  - name: DB_URI
    value: mongodb://root:4jNg203ZD7Fj@shared-mongodb-0.shared-mongodb-headless.shared-mongodb.svc.cluster.local:27017/fw-services?authSource=admin&readPreference=nearest&w=majority&replicaSet=rs0
  - name: CHANNELS_URI
    value: redis://redis-master.redis.svc.cluster.local:6379
  image:
    name: fw-services
    pullPolicy: Always
    repository: fwinternal.azurecr.io
    tag: 9ede53174ea7f95159a5ad778d91cda5dbb41835
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    enabled: true
    hosts:
    - host: fwservices.dev.financewise.com.br
      paths:
      - /
    tls:
    - hosts:
      - fwservices.dev.financewise.com.br
      secretName: fwservices.dev.financewise.com.br
  keycloak:
    client_id: gateway-services
    client_secret: gw4WGiIbZoeuySpitvnthgyuPnEHlRtX
    well_known_url: https://keycloak.dev.financewise.com.br/realms/fwise/.well-known/openid-configuration
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    tcpSocket:
      port: 3000
    timeoutSeconds: 1
  name: fw-services
  nodeSelector: {}
  readinessProbe:
    failureThreshold: 5
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    tcpSocket:
      port: 3000
    timeoutSeconds: 1
  replicaCount: 1
  resources:
    limits:
      cpu: 3000m
      memory: 1000Mi
    requests:
      cpu: 200m
      memory: 1000Mi
  tolerations: []
  updateStrategy: RollingUpdate
autoscaling:
  enabled: false
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 3
  targetCPUUtilizationPercentage: null
global:
  clusterDomain: cluster.local
  domainName: dev.financewise.com.br
  editor: FinanceWise
  imagePullSecrets:
  - name: regsecret
  monitoring:
    datadog:
      debug: false
      enabled: false
      env: env_name
      tennant: client_name
  namespace: financewise
  pullPolicy: Always
  updateStrategy: RollingUpdate
